name: Events Demo 1
on:
  pull_request:
    # only trigger event if pull request is either opened or edited
    types: [opened, edited]
    # single * means any character other then /
    # doubble * means any characters including /
    branches: [master, dev-*, releases/**]
  workflow_dispatch:
  push:
    branches: [master, dev-*, releases/**]
    # only trigger workflow if any files changes in the given folder
    # paths: ['.github/workflows/*']

    # Dont trigger the workflow if any file changes in the given path
    # paths-ignore: ['.github/workflows/*']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
